name: Deploy to EC2 Instance

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 14 # Change this to the desired Node.js version

      - name: Install npm dependencies
        run: npm install

      - name: Deploy to my EC2 instance
        env:
          PRIVATE_KEY: ${{ secrets.SSH_KEY }}
          HOSTNAME: ${{ secrets.HOST_IP }}
          USER_NAME: ${{ secrets.HOST_USER }}
          TARGET: "/home/ubuntu/Three-tierapp/backend/final"
        run: |
          echo "$PRIVATE_KEY" > abhijet && chmod 600 abhijet
          ssh -o StrictHostKeyChecking=no -i abhijet ${USER_NAME}@${HOSTNAME} '
            sudo dpkg --configure -a &&
            sudo apt-get update &&
            sudo apt-get install -y nodejs &&
            sudo apt-get install -y npm &&
            cd /home/ubuntu/Three-tierapp/backend/final &&
            sudo npm start
          '
