name: Deploy to EC2 Instance

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 18

      - name: Install npm dependencies
        run: npm install

      - name: Deploy to EC2
        env:
          PRIVATE_KEY: ${{ secrets.SSH_KEY }}
          HOSTNAME: ${{ secrets.HOST_IP }}
          USER_NAME: ${{ secrets.HOST_USER }}
        run: |
          echo "$PRIVATE_KEY" > key.pem && chmod 600 key.pem
          ssh -o StrictHostKeyChecking=no -i key.pem ${USER_NAME}@${HOSTNAME} '
            cd /home/ubuntu &&
            sudo docker stop $(docker ps -a -q) &&
            sudo docker rm $(docker ps -a -q) &&
            sudo docker rmi -f $(docker images -q) &&
            sudo docker pull ritikvirus/portfolioubuntu:${{ steps.taggerDryRun.outputs.new_tag }} &&
            sudo docker rm springboot || true &&
            sudo docker run -d -p 8080:80 --name portfolio ritikvirus/portfolioubuntu:${{ steps.taggerDryRun.outputs.new_tag }}
            echo ${{ github.sha }}
          '

