name: Deploy to EC2 Instance

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 18

      - name: Install npm dependencies
        run: npm install

      - name: Deploy to my EC2 instance
        uses: easingthemes/ssh-deploy@v2.1.5
        env:
          SSH_PRIVATE_KEY: ${{ secrets.DEPLOY_SSH_PRIVATE_KEY }}
          SOURCE: "./"
          REMOTE_HOST: "ec2-35-154-185-167.ap-south-1.compute.amazonaws.com"
          REMOTE_USER: "ubuntu"
          TARGET: "/home/ubuntu/Three-tierapp/backend/final"

      - name: Deploy app
        run: |
          cd /home/ubuntu/Three-tierapp/backend/final
          npm start

