name: Deploy to EC2 Instance

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 18

      - name: Install npm dependencies
        run: npm install

      - name: Deploy to EC2
        env:
          PRIVATE_KEY: ${{ secrets.DEPLOY_SSH_PRIVATE_KEY }}
          HOSTNAME: ${{ secrets.HOST_IP }}
          USER_NAME: ${{ secrets.HOST_USER }}
        run: |
          echo "$PRIVATE_KEY" > abhijet.pem
          chmod 600 abhijet.pem
          npm_path=$(which npm) # Get the path to the npm executable
          ssh -o StrictHostKeyChecking=no -i abhijet.pem ${USER_NAME}@${HOSTNAME} "
            cd /home/ubuntu/Three-tierapp/backend/final &&
            $npm_path install" # Install dependencies

          # Now start the application
          ssh -o StrictHostKeyChecking=no -i abhijet.pem ${USER_NAME}@${HOSTNAME} "
            cd /home/ubuntu/Three-tierapp/backend/final &&
            $npm_path start" # Start the application
