name: Deploy to EC2 Instance

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    env:
      SERVER_NAME: ip-172-31-47-166
      SERVER_IP: 35.154.185.167
      DEPLOY_PATH: /home/ubuntu/Three-tierapp/backend/builds
      PRIVATE_KEY: ${{ secrets.DEPLOY_SSH_PRIVATE_KEY }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 18

      - name: Install npm dependencies
        run: npm install

      - name: Deploy to EC2 Instance
        run: |
          ssh -o StrictHostKeyChecking=no -i $PRIVATE_KEY ubuntu@$SERVER_IP 'cd $DEPLOY_PATH && git pull'
