name: Deploy to EC2 Instance

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 18

      - name: Install npm dependencies
        run: npm install

      - name: Configure Git
        run: |
          git config --global user.email "you@example.com"
          git config --global user.name "Your Name"
          git config --global credential.helper store
          echo "https://github.com:${{ secrets.GH_TOKEN }}@github.com" > ~/.git-credentials

      - name: Deploy to EC2 Instance
        run: |
          # Copy your application files to your EC2 instance using the private key
          scp -i /root/.ssh/id_rsa -r ./* ubuntu@35.154.185.167:/home/ubuntu/Three-tierapp/backend/builds
        env:
          YOUR_INSTANCE_IP: 35.154.185.167


